#!/bin/bash

SELF=$(readlink -f "$0")
HERE=${SELF%/*}
export HERE
export PATH="${HERE}/usr/bin/:${HERE}/usr/sbin/:${HERE}/usr/games/:${HERE}/bin/:${HERE}/sbin/${PATH:+:$PATH}"
export LD_LIBRARY_PATH="${HERE}/usr/lib/:${HERE}/usr/lib/i386-linux-gnu/:${HERE}/usr/lib/x86_64-linux-gnu/:${HERE}/usr/lib32/:${HERE}/usr/lib64/:${HERE}/lib/:${HERE}/lib/i386-linux-gnu/:${HERE}/lib/x86_64-linux-gnu/:${HERE}/lib32/:${HERE}/lib64/${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
export PYTHONPATH="${HERE}/usr/share/pyshared/${PYTHONPATH:+:$PYTHONPATH}"
export XDG_DATA_DIRS="${HERE}/usr/share/${XDG_DATA_DIRS:+:$XDG_DATA_DIRS}"
export PERLLIB="${HERE}/usr/share/perl5/:${HERE}/usr/lib/perl5/${PERLLIB:+:$PERLLIB}"
export GSETTINGS_SCHEMA_DIR="${HERE}/usr/share/glib-2.0/schemas/${GSETTINGS_SCHEMA_DIR:+:$GSETTINGS_SCHEMA_DIR}"
export QT_PLUGIN_PATH="${HERE}/usr/lib/qt4/plugins/:${HERE}/usr/lib/i386-linux-gnu/qt4/plugins/:${HERE}/usr/lib/x86_64-linux-gnu/qt4/plugins/:${HERE}/usr/lib32/qt4/plugins/:${HERE}/usr/lib64/qt4/plugins/:${HERE}/usr/lib/qt5/plugins/:${HERE}/usr/lib/i386-linux-gnu/qt5/plugins/:${HERE}/usr/lib/x86_64-linux-gnu/qt5/plugins/:${HERE}/usr/lib32/qt5/plugins/:${HERE}/usr/lib64/qt5/plugins/${QT_PLUGIN_PATH:+:$QT_PLUGIN_PATH}"
#EXEC=$(grep -e '^Exec=.*' "${HERE}"/*.desktop | head -n 1 | cut -d "=" -f 2 | cut -d " " -f 1)
#exec "${EXEC}" "$@"

# Set the AppDir as the current directory
cd "$(dirname "$0")"

if [ ! -d "$HOME/Sefaria-Desktop-Unofficial" ]; then
    echo "Copying Database to $HOME/Sefaria-Desktop-Unofficial..."
    mkdir -p "$HOME/Sefaria-Desktop-Unofficial/log"
    cp -r "${HERE}/data/db" "$HOME/Sefaria-Desktop-Unofficial"
else
    echo "Database already exists at $HOME/Sefaria-Desktop-Unofficial"
fi

is_mongod_running() {
    pgrep mongod >/dev/null
    return $?
}

# Check if MongoDB is already running
if is_mongod_running; then
    echo "MongoDB is already running"
else
    echo "Starting MongoDB..."
    ${HERE}/usr/bin/mongod --quiet --fork --logpath "$HOME/Sefaria-Desktop-Unofficial/log/mongodb.log" --dbpath "$HOME/Sefaria-Desktop-Unofficial/db" 2>&1 1>/dev/null &
fi

is_redis_running() {
    pgrep redis-server >/dev/null
    return $?
}

# Check if Redis is already running
if is_redis_running; then
    echo "Redis is already running"
else
    echo "Starting Redis..."
    ${HERE}/usr/bin/redis-server --daemonize yes &
fi

# Start the Sefaria server
echo "Starting Sefaria..."
echo "This takes a minute or two, Please wait..."
${HERE}/python3.8.13-cp38-cp38-manylinux2010_x86_64.AppDir/opt/python3.8/bin/python3.8 ${HERE}/workspaces/Sefaria-Project/manage.py runserver 2>/dev/null
