#!/bin/bash

# Set the AppDir as the current directory
cd "$(dirname "$0")"

# Start MongoDB
./usr/bin/mongod --fork --logpath var/log/mongodb.log --dbpath data/db

# Start Redis
./usr/bin/redis-server &

# Wait for MongoDB and Redis to start
sleep 5

# Start the Sefaria server
./python3.8.13-cp38-cp38-manylinux2010_x86_64.AppDir/AppRun manage.py runserver

# Keep the script running
wait
