name: Run build.sh inside /workspaces

on:
  workflow_dispatch:

jobs:
  run-ls:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Docker Run
      run: |
        docker run -v $(pwd):/workspaces ghcr.io/orxaicom/sefaria-container-unofficial:latest /bin/bash -c "cd /workspaces && chmod +x build.sh && ./build.sh"

    - name: Upload AppImage
      uses: actions/upload-artifact@v4
      with:
        name: MyApp-x86_64.AppImage
        path: /artifacts
