name: Run build.sh in GHCR image

on:
  workflow_dispatch:

jobs:
  run-ls:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Docker Run
      run: |
        docker run -v $(pwd):/workspaces ghcr.io/orxaicom/sefaria-container-unofficial:latest /bin/sh -c "cd /workspaces && chmod +x build.sh && ./build.sh"
