name: Run build.sh in GHCR image

on:
  workflow_dispatch:

jobs:
  run-ls:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Run build.sh in GHCR image
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace \
          ghcr.io/orxaicom/sefaria-container-unofficial:latest \
          chmod +x ./build.sh && ./build.sh
